# 교보문고 베스트셀러 리스트 중복 제거 및 중복 횟수 집계

같은 폴더(또는 지정 경로)에 있는 여러 개의 `교보문고_종합_베스트셀러_상품리스트*.xlsx` 파일을 모두 읽어
1. 하나로 합치고
2. `상품코드`(ISBN) 기준으로 중복을 제거한 상품 리스트를 만들고
3. 각 상품이 전체 파일들에서 몇 번 등장했는지 `중복횟수` 열로 추가하여
4. 새 엑셀 파일로 저장합니다.

In [13]:
import glob
import pandas as pd

INPUT_DIR = "../data/raw/top-list"
FILE_PATTERN = "교보문고_종합_베스트셀러_상품리스트*.xlsx"

# 중복 판단 기준 컬럼 (상품코드=ISBN 기준으로 동일 상품 판단)
KEY_COLUMN = "상품코드"

OUTPUT_PATH = "../data/processed/교보문고_주간_베스트셀러_중복제거_리스트.xlsx"

In [14]:
files = sorted(glob.glob(f"{INPUT_DIR}/{FILE_PATTERN}"))
print(f"발견된 파일 {len(files)}개")
for f in files:
    print(" -", f)

발견된 파일 48개
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (15).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (16).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (17).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (18).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (19).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (20).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (21).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (22).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (23).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (24).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (25).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (26).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (27).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (28).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (29).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (30).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (31).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (32).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (33).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (34).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (35).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (36).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (37).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (38).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (39).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (40).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (41).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (42).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (43).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (44).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (45).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (46).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (47).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (48).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (49).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (50).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (51).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (52).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (53).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (54).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (55).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (56).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (57).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (58).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (59).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (60).xlsx
 - ../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (61).xlsx

In [15]:
# 모든 파일을 읽어 하나의 DataFrame으로 합치기 (어느 파일에서 왔는지 표시)
df_list = []
for f in files:
    tmp = pd.read_excel(f, dtype={KEY_COLUMN: str})
    tmp["출처파일"] = f
    df_list.append(tmp)

df_all = pd.concat(df_list, ignore_index=True)
print(f"합친 전체 행 수: {len(df_all)}")
df_all.head()

c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

합친 전체 행 수: 962

c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\USER\Desktop\synapse-summer\literec-system\notebook\.venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,순위,상품코드,판매상품 ID,상품명,정가,판매가,할인율,적립율,적립예정포인트,인물,출판사,발행(출시)일자,분야,출처파일
0,1,9788937460586,S000000620195,싯다르타,"8,000","7,200",10%,5%,400,헤르만 헤세,민음사,20020120,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....
1,2,9788925588735,S000000479333,프로젝트 헤일메리,"22,000","19,800",10%,5%,"1,100",앤디 위어,알에이치코리아,20260219,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....
2,3,9791198547514,S000211748790,수족관,"17,700","15,930",10%,5%,880,유래혁,포스터샵,20240111,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....
3,4,9791141602376,S000216796615,안녕이라 그랬어(집에디션 리커버),"16,800","15,120",10%,5%,840,김애란,문학동네,20250620,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....
4,5,9788998441012,S000001632467,모순,"13,000","11,700",10%,5%,650,양귀자,쓰다,20130401,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....

In [16]:
# 상품코드 기준 중복 횟수 계산
dup_counts = df_all.groupby(KEY_COLUMN).size().rename("중복횟수")

# 중복 제거 (첫 번째 등장 행만 남김), 순위/출처파일처럼 파일마다 달라지는 정보는 참고용으로만 유지
df_unique = df_all.drop_duplicates(subset=KEY_COLUMN, keep="first").copy()

# 중복횟수 컬럼 붙이기
df_unique = df_unique.merge(dup_counts, on=KEY_COLUMN, how="left")

# 보기 좋게 정렬: 중복횟수 많은 순 -> 상품명 순
df_unique = df_unique.sort_values(by=["중복횟수", "상품명"], ascending=[False, True]).reset_index(drop=True)

print(f"중복 제거 후 고유 상품 수: {len(df_unique)}")
df_unique.head(20)

중복 제거 후 고유 상품 수: 88

,순위,상품코드,판매상품 ID,상품명,정가,판매가,할인율,적립율,적립예정포인트,인물,출판사,발행(출시)일자,분야,출처파일,중복횟수
0,12,9788937473401,S000200550189,급류,"14,000","12,600",10%,5%,700,정대건,민음사,20221222,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,48
1,5,9788998441012,S000001632467,모순,"13,000","11,700",10%,5%,650,양귀자,쓰다,20130401,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,48
2,17,9788936439743,S000216111714,혼모노,"18,000","16,200",10%,5%,900,성해나,창비,20250328,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,48
3,4,9791141602376,S000216796615,안녕이라 그랬어(집에디션 리커버),"16,800","15,120",10%,5%,840,김애란,문학동네,20250620,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,47
4,15,9788936434120,S000000610612,소년이 온다,"15,000","13,500",10%,5%,750,한강,창비,20140519,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (17)....,45
5,7,9791199305304,S000217089705,자몽살구클럽,"12,000","10,800",10%,5%,600,한로로,어센틱,20250725,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,45
6,1,9788937460586,S000000620195,싯다르타,"8,000","7,200",10%,5%,400,헤르만 헤세,민음사,20020120,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,44
7,14,9788937460449,S000000620181,데미안,"8,000","7,200",10%,5%,400,헤르만 헤세,민음사,20090120,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,37
8,2,9788925588735,S000000479333,프로젝트 헤일메리,"22,000","19,800",10%,5%,"1,100",앤디 위어,알에이치코리아,20260219,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,37
9,11,9788937461798,S000000620316,브람스를 좋아하세요,"10,000","9,000",10%,5%,500,프랑수아즈 사강,민음사,20080502,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,34
10,19,9788998441074,S000001632473,나는 소망한다 내게 금지된 것을,"15,000","13,500",10%,5%,750,양귀자,쓰다,20190420,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (29)....,33
11,9,9791194530701,S000218438100,괴테는 모든 것을 말했다,"17,000","15,300",10%,5%,850,스즈키 유이,리프,20251118,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (14)....,27
12,20,9791141602451,S000217503188,절창,"18,000","16,200",10%,5%,900,구병모,문학동네,20250917,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (22)....,27
13,17,9788925554990,S000000478177,스토너,"16,800","15,120",10%,5%,840,존 윌리엄스,알에이치코리아,20150102,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (36)....,25
14,16,9788936434595,S000000610650,채식주의자,"17,000","15,300",10%,5%,850,한강,창비,20220328,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (38)....,24
15,19,9791170612759,S000217048850,가공범,"22,000","19,800",10%,5%,"1,100",히가시노 게이고,북다,20250721,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (38)....,21
16,19,9791124038192,S000218969272,나의 완벽한 장례식,"19,000","17,100",10%,5%,950,조현선,북로망스,20260121,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (18)....,20
17,20,9791167372864,S000201621499,구의 증명(리커버판),"12,000","10,800",10%,5%,600,최진영,은행나무,20230426,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (17)....,16
18,16,9788954682152,S000000781116,작별하지 않는다,"16,800","15,120",10%,5%,840,한강,문학동네,20210909,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (23)....,16
19,19,9788954681155,S000000781065,홍학의 자리,"14,000","12,600",10%,5%,700,정해연,엘릭시르,20210726,소설,../data/raw/top-list\교보문고_종합_베스트셀러_상품리스트 (19)....,15

In [17]:
# 중복된 상품(2회 이상 등장)만 확인
dup_only = df_unique[df_unique["중복횟수"] > 1]
print(f"여러 파일에 중복 등장한 상품 수: {len(dup_only)}")
dup_only[["상품코드", "상품명", "출판사", "중복횟수"]]

여러 파일에 중복 등장한 상품 수: 67

             상품코드                 상품명   출판사  중복횟수
0   9788937473401                  급류   민음사    48
1   9788998441012                  모순    쓰다    48
2   9788936439743                 혼모노    창비    48
3   9791141602376  안녕이라 그랬어(집에디션 리커버)  문학동네    47
4   9788936434120              소년이 온다    창비    45
..            ...                 ...   ...   ...
62  9788936439965                아코디언    창비     2
63  9788932925783            영혼의 왈츠 1  열린책들     2
64  9788937463952                  월든   민음사     2
65  9791193904565       일곱 번째는 내가 아니다   서삼독     2
66  9791159922527            저항의 멜랑콜리    알마     2

[67 rows x 4 columns]

In [18]:
# 결과 저장
df_unique.to_excel(OUTPUT_PATH, index=False)
print(f"저장 완료: {OUTPUT_PATH}")

저장 완료: ../data/processed/교보문고_주간_베스트셀러_중복제거_리스트.xlsx

In [19]:
df_weekly = pd.read_excel("../data/processed/교보문고_주간_베스트셀러_중복제거_리스트.xlsx")
df_monthly = pd.read_excel("../data/processed/교보문고_월간_베스트셀러_중복제거_리스트.xlsx")

df_combined = pd.concat([df_weekly, df_monthly], ignore_index=True)
df_combined = df_combined.drop_duplicates(subset="상품코드", keep="first")
df_combined.to_csv("../data/processed/교보문고_주간월간_통합_리스트.csv", index=False, encoding="utf-8-sig")